x-db: &db
  image: postgres:13.3
  healthcheck:
    test:
      [
        "CMD-SHELL",
        "pg_isready",
        "-q",
        "-d",
        "${DB_NAME}",
        "-U",
        "${DB_USER}",
      ]
    interval: 10s
    timeout: 10s
    retries: 5
  restart: always
  environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}

services:
  db:
    <<: *db
    container_name: url-shortener-db
    volumes:
      - ${DB_STORAGE}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

  db-test:
    <<: *db
    container_name: url-shortener-db-test
    volumes:
      - ${DB_STORAGE}-test:/var/lib/postgresql/data
    ports:
      - 5433:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: url-shortener-app
    volumes:
      - ${APP_STORAGE}/app:/app/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=url-shortener-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"