FROM python:3.12

WORKDIR /app

# # Set Python path to include the current directory
# ENV PYTHONPATH=/app

COPY requirements.txt .

RUN pip install -r requirements.txt

# Copy the entire app directory and necessary files
COPY app/ ./app/
COPY start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]